package maven.plugin.focusns;

/*
 * #%L
 * Focusns Maven Plugin
 * %%
 * Copyright (C) 2013 FocusSNS
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 2.1 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public 
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */


import maven.plugin.focusns.setting.DatabaseWizard;
import maven.plugin.focusns.setting.OpenApiWizard;
import maven.plugin.focusns.setting.ServerWizard;
import maven.plugin.focusns.setting.Wizard;
import maven.plugin.focusns.utils.Properties;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Mojo;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

@Mojo(name = "setup")
public class SetupMojo extends AbstractMojo {

    private static final String RUNTIME_NAME = ".focusns";
    private static final String RUNTIME_BASE = System.getProperty("user.home");
    private static final String RUNTIME_PATH = RUNTIME_BASE + File.separator + RUNTIME_NAME;
    //

    private static final Wizard databaseWizard = new DatabaseWizard();
    private static final Wizard openApiWizard = new OpenApiWizard();
    private static final Wizard serverWizader = new ServerWizard();

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        try {
            //
            Scanner scanner = new Scanner(System.in);
            //
            printWelcome(scanner);
            //
            Properties globalSettings = new Properties();
            //
            databaseWizard.setup(scanner, globalSettings);
            //
            // openApiWizard.setup(scanner, globalSettings);
            //
            serverWizader.setup(scanner, globalSettings);
            //
            storeToRuntime(globalSettings);
            //
            printEnjoyment(scanner);
            //
        } catch (Exception e) {
            throw new MojoExecutionException(e.getMessage(), e);
        }
    }

    private static void printWelcome(Scanner scanner) {
        StringBuilder welcome = new StringBuilder();
        welcome.append("######################################\n");
        welcome.append("#                                    #\n");
        welcome.append("#     欢迎进入 FocusSNS 安装程序       #\n");
        welcome.append("#     当前版本 2.0.0                  #\n");
        welcome.append("#                                    #\n");
        welcome.append("######################################\n");
        //
        System.out.println(welcome);
        //
        System.out.print("如需退出安装程序，请输入【exit】：");
        String exit = scanner.nextLine();
        if ("exit".equalsIgnoreCase(exit)) {
            System.exit(0);
        }
    }

    private static void printEnjoyment(Scanner scanner) {
        StringBuilder enjoyment = new StringBuilder();
        enjoyment.append("FocusSNS 已经安装成功，开始享用吧...");
        //
        System.out.println(enjoyment);
        // press any key to exit
        scanner.nextLine();
    }

    private static void storeToRuntime(Properties globalSettings) throws IOException {
        File runtime = new File(RUNTIME_PATH);
        if (!runtime.exists()) {
            runtime.mkdirs();
        }
        //
        File application = new File(RUNTIME_PATH + File.separator + "application.properties");
        if (application.exists()) {
            application.createNewFile();
        }
        //
        globalSettings.store(new FileWriter(application), "Generated by FocusSNS Installer");
    }

}
